### ISSUE TITLE
tag2ts 함수

### ISSUE THREAD

**Issue by Hyerin0407** [ceo21ckim/Aspect-Based-Sentiment-Analysis#1]
안녕하세요!

    def tag2ts(ts_tag_sequence):

    n_tags = len(ts_tag_sequence)
    ts_sequence, sentiments = [], []
    begin, end = -1, -1
    
    for i in range(n_tags):
        ts_tag = ts_tag_sequence[i]
        eles = ts_tag.split('-')
        
        if len(eles) == 2:
            pos, sentiment = eles
        else:
            pos, sentiment = 'O', 'O'
        
        if sentiment != 'O':
            sentiments.append(sentiment)
        
        if pos == 'S':
            ts_sequence.append((i, i, sentiment))
            sentiments = []
            
        elif pos == 'B':
            beg = i 
            if len(sentiments) > 1:
                sentiments = [sentiments[-1]]
        
        elif pos == 'E':
            end = i
            
            if end > begin > -1 and len(set(sentiments)) == 1:
                ts_sequence.append((begin, end, sentiment))
                sentiments = []
                begin, end = -1, -1
                
    return ts_sequence

`begin, end = -1, -1` 이 부분에서 논문의 코드에서는 `beg`라고 사용하고 있는데 혹시 `begin`으로 바꾸신 이유가 있으실까요?
`beg = i` 로 지정했으면 `beg`이랑 비교를 해야할 것 같은데, `end > begin > -1` 여기에서는 또 `begin`을 사용하고 있어서 혹시 어떤 이유가 있어서 바꾸신건지, 오타인건지 궁금합니다!

**Comment by ceo21ckim** [comment]
코드에 실수가 있었네요. beg로 사용하여야 합니다. 감사합니다.
